author: Luif C. # 作者
description: Luif C. の 部落格
keyword: hack, coding
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: valine

# gitment config
# gitment_owner: 
# gitment_repo: 
# gitment_oauth_id: 
# gitment_oauth_secret: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

# valine config:

valine_app_id: # add your leancloud appId here 
valine_app_key: # add your leancloud appKey. It's a client key, so it's considered being leaked
valine_notify: false
valine_verify: false
valine_placeholder: leave a comment
valine_avatar: mm
valine_page_size: 10
valine_visitor: true


baidu_id: 

# disqus config
disqus_shortname:  

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://i.loli.net/2019/02/27/5c76668f59203.jpg
  description: "随手写写."
  weibo_username: 
  twitter_username: 
  github_username: louiechan
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
